services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  backend:
    image: latcharit/se331-backend:latest
    ports:
      - 8999:8080
    environment:
      - JAVA_PROFILE=prod
    depends_on:
      - db
    restart: on-failure
